# Generated by Django 4.2.4 on 2023-08-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, choices=[('family', 'family'), ('friend', 'friend'), ('Cousin', 'Cousin'), ('In-Law', 'In-Law'), ('Others', 'Others')], max_length=100, null=True)),
            ],
        ),
    ]
