# Generated by Django 4.2.4 on 2023-08-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_adduser_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adduser',
            name='relation',
        ),
        migrations.AddField(
            model_name='adduser',
            name='relationship',
            field=models.CharField(blank=True, choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Mother', 'Mother'), ('Father', 'Father'), ('Cousin', 'Cousin'), ('In-Law', 'In-Law'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
